language: ruby
cache: bundler

rvm:
  - jruby
  - 2.2.0

script: 'bundle exec rake'

bundler_args: --without development debug

notifications:
  email:
    recipients:
      - jakcharlton@gmail.com
    on_failure: change
    on_success: never
